In [56]:
import numpy as np

In [2]:
a= np.array([3, 1, -2])
b= np.array([4, 1, 7])
c= np.array([1, -3, 4])

In [3]:
a.dot(b)

np.int64(-1)

In [4]:
a.dot(c)

np.int64(-8)

In [6]:
(a.dot(c) / a.dot(b))*b

array([32.,  8., 56.])

In [48]:
def factorial(k):
    ans = 1
    for i in range(1, k+1):
        ans *= i
    return ans

In [7]:
def C(n, r):
    if r > n:
        return 0
    if r == 0 or r == n:
        return 1
    num = 1
    for i in range(n, n-r, -1):
        num *= i
    den = 1
    for i in range(1, r+1):
        den *= i
    return num // den

In [49]:
def S(n, k):
    ans = 0
    for r in range(0, k):
        print(f"C({k}, {r}) * {k-r}**({k}-{r}) * ((-1)**({r}))")
        ans += C(k, r) * (k-r)**(n) * ((-1)**(r))
    return ans // factorial(k)

In [52]:
S(3, 2)

C(2, 0) * 2**(2-0) * ((-1)**(0))
C(2, 1) * 1**(2-1) * ((-1)**(1))


3

In [43]:
C(1, 0) * 1**(1-0) * (-1)**(0)

1

In [40]:

C(3, 1) * 2**(3-1) * ((-1)**(1))


-12

In [53]:
S(5, 4)

C(4, 0) * 4**(4-0) * ((-1)**(0))
C(4, 1) * 3**(4-1) * ((-1)**(1))
C(4, 2) * 2**(4-2) * ((-1)**(2))
C(4, 3) * 1**(4-3) * ((-1)**(3))


10

In [54]:
l = 23/14

In [55]:
28 * np.array([3 * l +1, 2 * l -1, l+2])

array([166.,  64., 102.])

In [59]:
P = np.array([2,-10,1])
A = np.array([1, -2, -3])
B= np.array([2, -1, 2])

In [ ]:
np.cross((A-P), B))

array([ 12,  -6, -15])

In [65]:
(6+5j)**(-2)

(0.002956194571351787-0.01612469766191884j)

In [67]:
(11-60j)/(61*61)

(0.002956194571351787-0.01612469766191884j)